# Generated by Django 6.1.1 on 2026-09-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_lessons_project_outcome_project_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal'), ('learning', 'Learning')], default='professional', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(help_text='Path under static files, for example portfolio/projects/example.png.', max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'image_path'), name='unique_project_screenshot_path')],
            },
        ),
    ]
